# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDbQhYOO3_gqQmkZ5GSsxgh3QkUXQ44
"""

from playwright.sync_api import sync_playwright

def fetch_products():
    base_url = "https://www.zendrop.com/collections/all"  # replace with your URL
    products = []

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context()
        page = context.new_page()

        url = base_url
        while True:
            print(f">>> Loading page: {url}")
            page.goto(url, wait_until="networkidle")

            try:
                page.wait_for_selector(".product-card", timeout=10000)  # adjust selector
            except:
                print("❌ Timeout waiting for product cards.")
                break

            items = page.query_selector_all(".product-card")
            for item in items:
                title_el = item.query_selector(".product-card__title")
                image_el = item.query_selector("img")
                price_el = item.query_selector(".price")
                link_el = item.query_selector("a")

                if title_el and image_el and price_el and link_el:
                    product = {
                        "title": title_el.inner_text().strip(),
                        "description": "",
                        "price": price_el.inner_text().strip().replace("$", ""),
                        "image": image_el.get_attribute("src"),
                        "product_url": link_el.get_attribute("href"),
                    }
                    products.append(product)

            next_link = page.query_selector("a.next")
            if next_link:
                url = next_link.get_attribute("href")
                if not url.startswith("http"):
                    url = "https://www.zendrop.com" + url
            else:
                print("✅ No more pages.")
                break

        browser.close()

    print(f"✅ Total products fetched from Zendrop: {len(products)}")
    return products