# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDbQhYOO3_gqQmkZ5GSsxgh3QkUXQ44
"""

import requests
from bs4 import BeautifulSoup

def fetch_go_supps_products():
    url = "https://www.gosupps.com/"
    try:
        response = requests.get(url, timeout=5)
        soup = BeautifulSoup(response.text, 'html.parser')
        products = []
        for item in soup.select('.product-item-info')[:10]:
            try:
                title = item.select_one('.product-item-link').get_text(strip=True)
                link = item.select_one('.product-item-link')['href']
                image = item.select_one('img')['data-src']
                price = item.select_one('.price').get_text(strip=True)
                products.append({
                    'title': title,
                    'link': link,
                    'image': image,
                    'price': price
                })
            except Exception:
                continue
        return products
    except Exception as e:
        print("Error fetching GoSupps products:", e)
        return []