# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDbQhYOO3_gqQmkZ5GSsxgh3QkUXQ44
"""

import os
import requests
from go_supps_connector import fetch_go_supps_products
from dotenv import load_dotenv

load_dotenv()

SHOPIFY_STORE_URL = os.getenv("SHOPIFY_STORE_URL")
SHOPIFY_API_KEY = os.getenv("SHOPIFY_API_KEY")
SHOPIFY_API_PASSWORD = os.getenv("SHOPIFY_API_PASSWORD")
AFFILIATE_REDIRECT_BASE = os.getenv("AFFILIATE_REDIRECT_BASE", "https://www.gosupps.com")  # Customize this

products = fetch_go_supps_products()

if not products:
    print("❌ No products were fetched. Please check go_supps_connector.py.")
    exit()

print(f"✅ Uploading {len(products)} products to Shopify...")

for product in products:
    product_link = f"{AFFILIATE_REDIRECT_BASE}/search?q={product['title'].replace(' ', '+')}"

    payload = {
        "product": {
            "title": product["title"],
            "body_html": f"<strong>Redirect to product:</strong> <a href='{product_link}' target='_blank'>Buy Now</a><br><img src='{product['image']}' />",
            "vendor": "GoSupps",
            "product_type": "Supplements",
            "tags": "affiliate, gosupps, imported",
            "variants": [{
                "price": product["price"].replace("US$", "").strip(),
                "inventory_quantity": 0  # not held in your inventory
            }]
        }
    }

    response = requests.post(
        f"{SHOPIFY_STORE_URL}/admin/api/2024-01/products.json",
        auth=(SHOPIFY_API_KEY, SHOPIFY_API_PASSWORD),
        json=payload
    )

    if response.status_code == 201:
        print(f"✅ Uploaded: {product['title']}")
    else:
        print(f"❌ Failed to upload: {product['title']}")
        print("→", response.status_code, response.text)