# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDbQhYOO3_gqQmkZ5GSsxgh3QkUXQ44
"""

import os
import requests
from go_supps_connector import fetch_go_supps_products

# Make sure the credentials are set correctly
SHOPIFY_STORE_URL = "https://tarasupp.myshopify.com"
SHOPIFY_API_KEY = "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"
SHOPIFY_API_PASSWORD = "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"  # Use same token if using private token

products = fetch_go_supps_products()

if not products:
    print("❌ No products were fetched. Please check go_supps_connector.py.")
    exit()

print(f"✅ Uploading {len(products)} products to Shopify...")

for product in products:
    payload = {
        "product": {
            "title": product["title"],
            "body_html": "<strong>Imported from GoSupps</strong>",
            "vendor": "GoSupps",
            "product_type": "Supplements",
            "images": [{"src": product["image"]}],
            "variants": [{
                "price": product["price"].replace("US$", "").strip(),
                "inventory_quantity": 10
            }]
        }
    }

    response = requests.post(
        f"{SHOPIFY_STORE_URL}/admin/api/2024-01/products.json",
        auth=(SHOPIFY_API_KEY, SHOPIFY_API_PASSWORD),
        json=payload
    )

    if response.status_code == 201:
        print(f"✅ Uploaded: {product['title']}")
    else:
        print(f"❌ Failed to upload: {product['title']}")
        print("→", response.status_code, response.text)