# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDbQhYOO3_gqQmkZ5GSsxgh3QkUXQ44
"""

import os
from dotenv import load_dotenv
import requests

# Load environment variables from .env file
load_dotenv()

SHOPIFY_STORE_URL = os.getenv("SHOPIFY_STORE_URL")
SHOPIFY_ACCESS_TOKEN = os.getenv("SHOPIFY_ACCESS_TOKEN")

def check_shopify_credentials():
    if not SHOPIFY_STORE_URL or not SHOPIFY_ACCESS_TOKEN:
        print("❌ Missing Shopify store URL or access token in environment variables.")
        return

    print("🔍 Checking Shopify product list...")

    url = f"{SHOPIFY_STORE_URL}/admin/api/2024-01/products.json"
    headers = {
        "X-Shopify-Access-Token": SHOPIFY_ACCESS_TOKEN,
        "Content-Type": "application/json"
    }

    try:
        response = requests.get(url, headers=headers)
    except Exception as e:
        print("❌ Error connecting to Shopify API:", e)
        return

    if response.status_code == 200:
        data = response.json()
        products = data.get("products", [])
        print(f"✅ Found {len(products)} product(s) in Shopify.")
        for p in products:
            print(f"→ {p['title']} | ID: {p['id']}")
    else:
        print("❌ Shopify API call failed.")
        print(f"→ Status: {response.status_code}")
        print("→ Response:", response.text)

if __name__ == "__main__":
    check_shopify_credentials()