# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDbQhYOO3_gqQmkZ5GSsxgh3QkUXQ44
"""

import os
from dotenv import load_dotenv

load_dotenv()

AFFILIATE_TAG = os.getenv("AMAZON_AFFILIATE_TAG", "tara0b6-20")
AMAZON_REGION = os.getenv("AMAZON_REGION", "com")
SEARCH_KEYWORD = os.getenv("AMAZON_SEARCH_KEYWORD", "electronics")

def fetch_products():
    search_url = f"https://www.amazon.{AMAZON_REGION}/s?k={SEARCH_KEYWORD}&tag={AFFILIATE_TAG}"

    products = [{
        "title": f"Top {SEARCH_KEYWORD} on Amazon",
        "description": "Buy the best products directly via our Amazon affiliate link.",
        "price": "29.99",
        "image": "https://via.placeholder.com/300x300.png?text=Amazon+Product",
        "product_url": search_url
    }]

    print(f"✅ Fetched {len(products)} from Amazon affiliate")
    return products

if __name__ == "__main__":
    items = fetch_products()
    for item in items:
        print(item)