# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDbQhYOO3_gqQmkZ5GSsxgh3QkUXQ44
"""

from datetime import datetime, date
from typing import List, Dict
import csv
from uuid import uuid4
import requests  # Make sure requests is installed (pip install requests)

# In-memory affiliate DB
_affiliate_db: Dict[str, List[Dict]] = {
    "A001": [
        {
            "affiliate_id": "binance001",
            "name": "Binance",
            "joined_date": date(2025, 7, 3).isoformat(),
            "earnings": 0.0,
            "referral_link": "https://www.binance.com/en/register?ref=CPA_00EDS8MQJG"
        }
    ]
}

def list_affiliates(agent_id: str) -> List[Dict]:
    return _affiliate_db.get(agent_id, [])

def get_affiliate_count(agent_id: str) -> int:
    return len(_affiliate_db.get(agent_id, []))

def get_affiliate_earnings(agent_id: str) -> float:
    return sum(a.get("earnings", 0.0) for a in _affiliate_db.get(agent_id, []))

def add_affiliate(agent_id: str, affiliate_data: Dict) -> None:
    jd = affiliate_data.get("joined_date")
    if isinstance(jd, str):
        affiliate_data["joined_date"] = jd  # keep ISO string
    _affiliate_db.setdefault(agent_id, []).append(affiliate_data)

def inject_global_affiliates(agent_id: str, csv_file_path: str, affiliate_codes: Dict[str, str]) -> List[Dict]:
    new_affiliates = []
    with open(csv_file_path, newline='', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            platform = row["Platform Name"]
            template_url = row["Website URL"]
            code = affiliate_codes.get(platform)
            if code:
                referral_url = template_url.replace("{affiliate_code}", code)
                affiliate_data = {
                    "affiliate_id": str(uuid4())[:8],
                    "name": platform,
                    "joined_date": datetime.now().date().isoformat(),
                    "earnings": 0.0,
                    "referral_link": referral_url
                }
                add_affiliate(agent_id, affiliate_data)
                new_affiliates.append(affiliate_data)
    return new_affiliates

def sync_affiliates_to_backend(agent_id: str, affiliates: List[Dict], backend_url: str) -> None:
    url = f"{backend_url}/api/agents/{agent_id}/affiliates/inject"
    try:
        response = requests.post(url, json=affiliates)
        response.raise_for_status()
        print(f"✅ Synced {len(affiliates)} affiliates to backend.")
    except Exception as e:
        print(f"⚠️ Failed to sync affiliates to backend: {e}")

if __name__ == "__main__":
    agent_id = "A001"
    csv_file = "global_affiliate_platforms.csv"
    affiliate_codes = {
        "Binance": "CPA_00EDS8MQJG",
        "Coinbase": "YOUR_COINBASE_CODE",
        "Crypto.com": "YOUR_CRYPTO_COM_CODE"
    }
    backend_base_url = "http://127.0.0.1:8000"  # Your running backend URL

    print(f"🚀 Injecting affiliates for agent: {agent_id}")
    new_affiliates = inject_global_affiliates(agent_id, csv_file, affiliate_codes)
    print(f"✅ Injection complete! Total affiliates now: {get_affiliate_count(agent_id)}")

    # Sync injected affiliates with backend
    sync_affiliates_to_backend(agent_id, new_affiliates, backend_base_url)

    # Optional: print all affiliate referral links for verification
    for aff in list_affiliates(agent_id):
        print(f"🔗 {aff['name']} – {aff['referral_link']}")