# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDbQhYOO3_gqQmkZ5GSsxgh3QkUXQ44
"""

from datetime import datetime

# Simulated in-memory affiliate database
_affiliate_db = {
    "A001": [
        {
            "affiliate_id": "binance001",
            "name": "Binance",
            "joined_date": "2025-07-03",
            "earnings": 0.0,
            "referral_link": "https://www.binance.com/activity/referral-entry/CPA?ref=CPA_00EDS8MQJG"
        }
    ]
}

def get_affiliate_details(agent_id):
    return _affiliate_db.get(agent_id, [])

def get_affiliate_count(agent_id):
    return len(_affiliate_db.get(agent_id, []))

def get_affiliate_earnings(agent_id):
    return sum(a.get("earnings", 0) for a in _affiliate_db.get(agent_id, []))

def add_affiliate(agent_id, affiliate_data):
    if agent_id not in _affiliate_db:
        _affiliate_db[agent_id] = []
    _affiliate_db[agent_id].append(affiliate_data)