# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MpDbQhYOO3_gqQmkZ5GSsxgh3QkUXQ44
"""

#!/bin/bash
# Launch Streamlit crypto dashboard from marketplace folder

cd "$(dirname "$0")"
streamlit run crypto/crypto_agent_module.py